name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy_user:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      #Build Image
      - name: Build Docker Image
        run: docker build . --file Dockerfile -t riobener/user-service:latest
      #Test container
      - name: Run Docker Container
        run: docker run -p 8081:8081 -d riobener/user-service:latest
      - name: sleep
        run: sleep 10
      - name: Docker ps
        run: docker ps
      - name: CURL
        run: curl http://localhost:8081/users/health
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pytest
        run: pip install pytest
      - name: Install requests
        run: pip install requests
      - name: Run tests
        run: pytest

      #Push image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push riobener/user-service:latest
